% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(tidyr)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(kableExtra)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{load\_prices }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(path, am\_eu, call\_put) \{}
  \FunctionTok{read\_csv}\NormalTok{(path) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{am\_eu =}\NormalTok{ am\_eu, }\AttributeTok{call\_put =}\NormalTok{ call\_put)}
\NormalTok{\}}

\NormalTok{df\_raw }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(}
  \FunctionTok{load\_prices}\NormalTok{(}\StringTok{"../calculated\_prices/american\_calls.csv"}\NormalTok{, }\StringTok{"american"}\NormalTok{, }\StringTok{"calls"}\NormalTok{),}
  \FunctionTok{load\_prices}\NormalTok{(}\StringTok{"../calculated\_prices/american\_puts.csv"}\NormalTok{, }\StringTok{"american"}\NormalTok{, }\StringTok{"puts"}\NormalTok{),}
  \FunctionTok{load\_prices}\NormalTok{(}\StringTok{"../calculated\_prices/european\_calls.csv"}\NormalTok{, }\StringTok{"european"}\NormalTok{, }\StringTok{"calls"}\NormalTok{),}
  \FunctionTok{load\_prices}\NormalTok{(}\StringTok{"../calculated\_prices/european\_puts.csv"}\NormalTok{, }\StringTok{"european"}\NormalTok{, }\StringTok{"puts"}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{true\_price =}\NormalTok{ option\_price) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{moneyness\_regime =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      call\_put }\SpecialCharTok{==} \StringTok{"calls"} \SpecialCharTok{\&}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ K }\SpecialCharTok{\textless{}} \FloatTok{0.95} \SpecialCharTok{\textasciitilde{}} \StringTok{"OTM"}\NormalTok{,}
\NormalTok{      call\_put }\SpecialCharTok{==} \StringTok{"calls"} \SpecialCharTok{\&}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ K }\SpecialCharTok{\textless{}=} \FloatTok{1.05} \SpecialCharTok{\textasciitilde{}} \StringTok{"ATM"}\NormalTok{,}
\NormalTok{      call\_put }\SpecialCharTok{==} \StringTok{"calls"} \SpecialCharTok{\textasciitilde{}} \StringTok{"ITM"}\NormalTok{,}
\NormalTok{      call\_put }\SpecialCharTok{==} \StringTok{"puts"} \SpecialCharTok{\&}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ K }\SpecialCharTok{\textless{}} \FloatTok{0.95} \SpecialCharTok{\textasciitilde{}} \StringTok{"ITM"}\NormalTok{,}
\NormalTok{      call\_put }\SpecialCharTok{==} \StringTok{"puts"} \SpecialCharTok{\&}\NormalTok{ S }\SpecialCharTok{/}\NormalTok{ K }\SpecialCharTok{\textless{}=} \FloatTok{1.05} \SpecialCharTok{\textasciitilde{}} \StringTok{"ATM"}\NormalTok{,}
\NormalTok{      call\_put }\SpecialCharTok{==} \StringTok{"puts"} \SpecialCharTok{\textasciitilde{}} \StringTok{"OTM"}
\NormalTok{    ),}
    \AttributeTok{time\_regime =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      T }\SpecialCharTok{\textless{}=} \FloatTok{0.1} \SpecialCharTok{\textasciitilde{}} \StringTok{"Short"}\NormalTok{,}
\NormalTok{      T }\SpecialCharTok{\textless{}=} \FloatTok{0.5} \SpecialCharTok{\textasciitilde{}} \StringTok{"Medium"}\NormalTok{,}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \StringTok{"Long"}
\NormalTok{    )}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 78863 Columns: 17
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr   (2): ticker, option_type
## dbl  (14): K, bid_price, ask_price, option_price, volume, open_interest, r, ...
## date  (1): expiration
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
## Rows: 68537 Columns: 17
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr   (2): ticker, option_type
## dbl  (14): K, bid_price, ask_price, option_price, volume, open_interest, r, ...
## date  (1): expiration
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
## Rows: 10467 Columns: 17
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr   (2): ticker, option_type
## dbl  (14): K, bid_price, ask_price, option_price, volume, open_interest, r, ...
## date  (1): expiration
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
## Rows: 11129 Columns: 17
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr   (2): ticker, option_type
## dbl  (14): K, bid_price, ask_price, option_price, volume, open_interest, r, ...
## date  (1): expiration
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df\_raw}

\NormalTok{df}\SpecialCharTok{$}\NormalTok{SK\_ratio }\OtherTok{\textless{}{-}}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{S }\SpecialCharTok{/}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{K}
\end{Highlighting}
\end{Shaded}

\section{Deskriptivní analýza}\label{deskriptivnuxed-analuxfdza}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{subset }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"SK\_ratio"}\NormalTok{, }\StringTok{"sigma"}\NormalTok{, }\StringTok{"q"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"T"}\NormalTok{)}

\NormalTok{df\_subset }\OtherTok{\textless{}{-}}\NormalTok{ df[subset]}

\FunctionTok{summary}\NormalTok{(df\_subset)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     SK_ratio            sigma               q                  r          
##  Min.   :  0.0318   Min.   :0.06288   Min.   :0.000000   Min.   :0.03381  
##  1st Qu.:  0.7018   1st Qu.:0.28593   1st Qu.:0.000000   1st Qu.:0.03653  
##  Median :  0.9883   Median :0.33893   Median :0.000000   Median :0.03738  
##  Mean   :  1.9595   Mean   :0.38777   Mean   :0.002244   Mean   :0.03711  
##  3rd Qu.:  1.3688   3rd Qu.:0.43143   3rd Qu.:0.002791   3rd Qu.:0.03764  
##  Max.   :430.6600   Max.   :1.38252   Max.   :0.136007   Max.   :0.04060  
##        T          
##  Min.   :0.00274  
##  1st Qu.:0.07945  
##  Median :0.39452  
##  Mean   :0.66106  
##  3rd Qu.:0.89589  
##  Max.   :2.89041
\end{verbatim}

Pokud bychom začínali od konce, \texttt{r} a \texttt{T} vypadají
rozumně. \texttt{r} se pohybuje mezi 3.3 \% až 4.1 \%, což vypadá vcelku
důvěryhodně, neb je v normách získáných ze zdroje bezrizikových mír.
\texttt{T} se pohybuje mezi 1 dnem a necelými 3 lety, nic extra
pozoruhodného. Medián i průměr se drží hodnoty pro první dny, což by
sedělo, neb většina opcí má krátkou expiraci.

Na \texttt{q} pozorujeme hodnoty od 0 \% do 13.6 \%. 13.6 \% je velmi
vysoké, a pro opce které jej maj, je to prudce vyšší než \texttt{r}.
Toto je z důvodu délky expirace: expirace pro tyto opce je 18 dní. Cena
opce klesne za krátký čas, což ``nafoukne'' \texttt{q}. Asi
akceptovatelné.

Pro \texttt{sigma} se data pohybují celkově mezi 6 \% a 138 \%, s prvním
a třetím kvartilem 28 \% a 43 \%. Rozložení dat celkově vypadá ok, ale
je nutno prozkoumat outliery. Hodnoty 138 \% patří indexu VIX, což je
index na volatilitě. V podstatě asi dává smysl, nutno na to dávat pozor.
Hodnoty 6.29\% patří měnovému indexu nad Eurem (?) (\^{}XDE). Euro je
asi stabilní, takže opět dává smysl.

\texttt{S/K} má první a třetí kvantil mezi hodnotami 0.7 a 1.36 a medián
0.98, což vypadá, jako že nám dává smysluplné hodnoty. Minimum v 0.03 a
maximum v 430.66 jsou extrémy, ale asi pochopitelné.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_sk }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(sigma)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_min}\NormalTok{(sigma, }\AttributeTok{n =} \DecValTok{25}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(ticker, am\_eu, call\_put, S, K, q, T, sigma, true\_price)}

\FunctionTok{print}\NormalTok{(top\_sk, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{n =} \DecValTok{25}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 33 x 9
##    ticker am_eu    call_put     S     K     q      T  sigma true_price
##    <chr>  <chr>    <chr>    <dbl> <dbl> <dbl>  <dbl>  <dbl>      <dbl>
##  1 ^XDE   european calls     116.  110      0 0.0658 0.0629       7.58
##  2 ^XDE   european calls     116.  114      0 0.0658 0.0629       6.2 
##  3 ^XDE   european calls     116.  116      0 0.0658 0.0629       3.19
##  4 ^XDE   european calls     116.  116.     0 0.0658 0.0629       4.35
##  5 ^XDE   european calls     116.  117      0 0.0658 0.0629       1.77
##  6 ^XDE   european calls     116.  118.     0 0.0658 0.0629       0.9 
##  7 ^XDE   european calls     116.  118.     0 0.0658 0.0629       2.31
##  8 ^XDE   european calls     116.  119      0 0.0658 0.0629       2.05
##  9 ^XDE   european calls     116.  121      0 0.0658 0.0629       0.52
## 10 ^XDE   european calls     116.  123      0 0.0658 0.0629       0.81
## 11 ^XDE   european calls     116.  120      0 0.318  0.0629       2.61
## 12 ^XDE   european calls     116.  120      0 0.567  0.0629       1.89
## 13 ^XDE   european puts      116.  116.     0 0.0658 0.0629       0.74
## 14 ^XDE   european puts      116.  117      0 0.0658 0.0629       0.79
## 15 ^XDE   european puts      116.  118.     0 0.0658 0.0629       1.28
## 16 ^XDE   european puts      116.  118      0 0.0658 0.0629       2.45
## 17 ^XDE   european puts      116.  119      0 0.0658 0.0629       3   
## 18 ^XDE   european puts      116.  120      0 0.0658 0.0629       2.63
## 19 ^XDE   european puts      116.  116      0 0.145  0.0629       0.75
## 20 ^XDE   european puts      116.  116      0 0.318  0.0629       2.65
## 21 ^XDE   european puts      116.  120      0 0.318  0.0629       4.14
## 22 ^XDE   european puts      116.  121      0 0.318  0.0629       2.87
## 23 ^XDB   european puts      134.  127      0 0.0658 0.0657       0.15
## 24 ^XDB   european puts      134.  137      0 0.0658 0.0657       4.8 
## 25 ^XDB   european puts      134.  126      0 0.318  0.0657       5   
## # i 8 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stats\_by\_ticker }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(ticker) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \FunctionTok{across}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(subset),}
      \FunctionTok{list}\NormalTok{(}
        \AttributeTok{min =} \SpecialCharTok{\textasciitilde{}} \FunctionTok{min}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{median =} \SpecialCharTok{\textasciitilde{}} \FunctionTok{median}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{max =} \SpecialCharTok{\textasciitilde{}} \FunctionTok{max}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{      ),}
      \AttributeTok{.names =} \StringTok{"\{col\}\_\{fn\}"}
\NormalTok{    )}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\item
  VIX, NVDA, NFLX mají extrémně malá minima \texttt{S/K}, měnové fondy
  (XDA, XDB, XDE, XDN) mají extrémně velká minima \texttt{S/K}. Extrémně
  malá maxima \texttt{S/K} pro měnové fondy, extrémně velká \texttt{S/K}
  pro AAPL, AMD, GOOGL, META, NFLX, NVDA, TSLA.
\item
  Význačně malé sigma pro měnové fondy, VIX má velmi vysoké
  \texttt{sigma} (až 138 \%). Došlo k destabilizaci NVDA a TSLA (vysoké
  rozdíly v sigma, stále v rozumných mírách).
\item
  PG a zvlášť KO mají velmi velké maximální \texttt{q}.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(stats\_by\_ticker)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0417}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0774}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0952}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0774}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0774}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0357}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 30\tabcolsep) * \real{0.0595}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
ticker
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SK\_ratio\_min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SK\_ratio\_median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SK\_ratio\_max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sigma\_min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sigma\_median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sigma\_max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
q\_min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
q\_median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
q\_max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
r\_min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
r\_median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
r\_max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
T\_min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
T\_median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
T\_max
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
AAPL & 0.4509818 & 1.1274545 & 61.764001 & 0.2211015 & 0.3139124 &
0.3206457 & 0 & 0.0034994 & 0.0210479 & 0.0338050 & 0.0374160 &
0.0406012 & 0.0027397 & 0.5589041 & 2.8904110 \\
AMD & 0.3843019 & 1.1290434 & 93.502002 & 0.5923509 & 0.6326559 &
0.6353343 & 0 & 0.0000000 & 0.0000000 & 0.0338798 & 0.0374620 &
0.0406012 & 0.0027397 & 0.4821918 & 2.8904110 \\
AMZN & 0.5609189 & 1.0342525 & 3.550933 & 0.2967328 & 0.3454151 &
0.3513897 & 0 & 0.0000000 & 0.0000000 & 0.0338300 & 0.0374160 &
0.0406012 & 0.0027397 & 0.4739726 & 2.8904110 \\
GOOGL & 0.4321846 & 1.0638056 & 76.594000 & 0.2859279 & 0.3037231 &
0.3216249 & 0 & 0.0027428 & 0.0175997 & 0.0338300 & 0.0374160 &
0.0406012 & 0.0027397 & 0.5671233 & 2.8904110 \\
JNJ & 0.6509444 & 1.2230000 & 3.246267 & 0.1641239 & 0.1903089 &
0.1952745 & 0 & 0.0194059 & 0.0666076 & 0.0339028 & 0.0374160 &
0.0394469 & 0.0027397 & 0.3945205 & 1.9890411 \\
KO & 0.6224167 & 1.0733333 & 2.507077 & 0.1560660 & 0.1669672 &
0.1780953 & 0 & 0.0246733 & 0.1360067 & 0.0339028 & 0.0374620 &
0.0394469 & 0.0027397 & 0.2410959 & 1.9890411 \\
META & 0.3650267 & 0.9453381 & 131.752002 & 0.3479135 & 0.3917281 &
0.3933121 & 0 & 0.0035167 & 0.0138781 & 0.0338300 & 0.0374160 &
0.0406012 & 0.0027397 & 0.4821918 & 2.8904110 \\
MSFT & 0.4574625 & 0.9206792 & 2.662571 & 0.2403629 & 0.2641411 &
0.2662377 & 0 & 0.0074942 & 0.0266127 & 0.0338300 & 0.0374160 &
0.0406012 & 0.0027397 & 0.4821918 & 2.8904110 \\
NFLX & 0.0318008 & 0.5126191 & 186.639999 & 0.3266234 & 0.3383830 &
0.3418921 & 0 & 0.0000000 & 0.0000000 & 0.0338300 & 0.0372727 &
0.0406012 & 0.0027397 & 0.6438356 & 2.8904110 \\
NVDA & 0.0684960 & 1.0253810 & 430.660004 & 0.3389305 & 0.4061966 &
0.4873938 & 0 & 0.0002365 & 0.0039495 & 0.0338798 & 0.0372978 &
0.0406012 & 0.0027397 & 0.4739726 & 2.8904110 \\
PG & 0.5477692 & 1.0246043 & 2.339286 & 0.1788702 & 0.1894792 &
0.1919587 & 0 & 0.0177175 & 0.0775085 & 0.0339028 & 0.0374620 &
0.0394469 & 0.0027397 & 0.2301370 & 1.9890411 \\
TSLA & 0.3758687 & 0.9965146 & 89.811999 & 0.4713487 & 0.5497188 &
0.6219018 & 0 & 0.0000000 & 0.0000000 & 0.0338300 & 0.0374160 &
0.0406012 & 0.0027397 & 0.3945205 & 2.8904110 \\
\^{}RUT & 0.5738460 & 1.0433564 & 3.020242 & 0.1925582 & 0.2300590 &
0.2311460 & 0 & 0.0000000 & 0.0000000 & 0.0338798 & 0.0374620 &
0.0406012 & 0.0027397 & 0.0904110 & 2.8904110 \\
\^{}VIX & 0.0804500 & 0.6771429 & 2.744000 & 1.1417870 & 1.3627813 &
1.3825220 & 0 & 0.0000000 & 0.0000000 & 0.0356494 & 0.0373145 &
0.0388212 & 0.0054795 & 0.2246575 & 0.6575342 \\
\^{}XDA & 0.9188000 & 1.0294203 & 1.340189 & 0.0810003 & 0.0981311 &
0.1016966 & 0 & 0.0000000 & 0.0000000 & 0.0352683 & 0.0374620 &
0.0381252 & 0.0602740 & 0.4821918 & 0.8958904 \\
\^{}XDB & 0.9526536 & 1.0106815 & 1.137017 & 0.0656558 & 0.0690917 &
0.0721381 & 0 & 0.0000000 & 0.0000000 & 0.0352683 & 0.0372978 &
0.0381252 & 0.0602740 & 0.3178082 & 0.8164384 \\
\^{}XDE & 0.9376951 & 0.9915136 & 1.074818 & 0.0628761 & 0.0770653 &
0.0776934 & 0 & 0.0000000 & 0.0000000 & 0.0352683 & 0.0372978 &
0.0380256 & 0.0602740 & 0.1479452 & 0.8082192 \\
\^{}XDN & 0.7851250 & 0.9398196 & 1.019508 & 0.0858056 & 0.0998056 &
0.1003061 & 0 & 0.0000000 & 0.0000000 & 0.0352683 & 0.0373000 &
0.0381252 & 0.0602740 & 0.1479452 & 0.8958904 \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(am\_eu }\SpecialCharTok{==} \StringTok{"american"}\NormalTok{, call\_put }\SpecialCharTok{==} \StringTok{"calls"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(ticker) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{max\_val =} \FunctionTok{pmax}\NormalTok{(}\FunctionTok{max}\NormalTok{(user\_bs, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
                         \FunctionTok{max}\NormalTok{(true\_price, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ user\_bs, }\AttributeTok{y =}\NormalTok{ true\_price)) }\SpecialCharTok{+}
  \FunctionTok{geom\_blank}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ max\_val, }\AttributeTok{y =}\NormalTok{ max\_val)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ticker, }\AttributeTok{nrow =} \DecValTok{3}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{4}\NormalTok{, }\AttributeTok{scales =} \StringTok{"free"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Black{-}Scholes price"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Market price"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{analysis_p2_files/analysis_p2_files/figure-latex/scatter-am-calls-1.pdf}}

\begin{itemize}
\item
  NFLX a NVDA velmi misshapen. Častý odhad ceny 0 když trh hodnotí více.
\item
  AAPL, AMZN, PG, KO plus-mínus drží ideální tvar. AMD, GOOGL, JNJ
  konzistentně přeceňují, META, MSFT podhodnocují. TSLA obecně
  nestabilní s vyšší hodnotou.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(am\_eu }\SpecialCharTok{==} \StringTok{"american"}\NormalTok{, call\_put }\SpecialCharTok{==} \StringTok{"puts"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(ticker) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{max\_val =} \FunctionTok{pmax}\NormalTok{(}\FunctionTok{max}\NormalTok{(user\_bs, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
                         \FunctionTok{max}\NormalTok{(true\_price, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ user\_bs, }\AttributeTok{y =}\NormalTok{ true\_price)) }\SpecialCharTok{+}
  \FunctionTok{geom\_blank}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ max\_val, }\AttributeTok{y =}\NormalTok{ max\_val)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ticker, }\AttributeTok{nrow =} \DecValTok{3}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{4}\NormalTok{, }\AttributeTok{scales =} \StringTok{"free"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Black{-}Scholes price"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Market price"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{analysis_p2_files/analysis_p2_files/figure-latex/scatter-am-puts-1.pdf}}

\begin{itemize}
\item
  NFLX a NVDA opět velmi misshapen, pro hodnotné opce silně přeceňujeme.
\item
  AMD, AAPL, GOOGL, JNJ, KO, PG celkem sedí, AMZN, META, MSFT, TSLA
  přeceňují
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(am\_eu }\SpecialCharTok{==} \StringTok{"european"}\NormalTok{, call\_put }\SpecialCharTok{==} \StringTok{"calls"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(ticker) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{max\_val =} \FunctionTok{pmax}\NormalTok{(}\FunctionTok{max}\NormalTok{(user\_bs, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
                         \FunctionTok{max}\NormalTok{(true\_price, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ user\_bs, }\AttributeTok{y =}\NormalTok{ true\_price)) }\SpecialCharTok{+}
  \FunctionTok{geom\_blank}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ max\_val, }\AttributeTok{y =}\NormalTok{ max\_val)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ticker, }\AttributeTok{nrow =} \DecValTok{3}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{scales =} \StringTok{"free"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Black{-}Scholes price"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Market price"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{analysis_p2_files/analysis_p2_files/figure-latex/scatter-eu-calls-1.pdf}}

RUT a VIX přeceňují. XDE a XDN all over the place.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(am\_eu }\SpecialCharTok{==} \StringTok{"european"}\NormalTok{, call\_put }\SpecialCharTok{==} \StringTok{"puts"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(ticker) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{max\_val =} \FunctionTok{pmax}\NormalTok{(}\FunctionTok{max}\NormalTok{(user\_bs, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
                         \FunctionTok{max}\NormalTok{(true\_price, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ user\_bs, }\AttributeTok{y =}\NormalTok{ true\_price)) }\SpecialCharTok{+}
  \FunctionTok{geom\_blank}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ max\_val, }\AttributeTok{y =}\NormalTok{ max\_val)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ticker, }\AttributeTok{nrow =} \DecValTok{3}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{scales =} \StringTok{"free"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Black{-}Scholes price"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Market price"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{analysis_p2_files/analysis_p2_files/figure-latex/scatter-eu-puts-1.pdf}}

RUT podceňuje, VIX ideální, XDB a XDE podceňuje.

\section{Analýza chyb}\label{analuxfdza-chyb}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{subset }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"ticker"}\NormalTok{, }\StringTok{"S"}\NormalTok{, }\StringTok{"K"}\NormalTok{, }\StringTok{"call\_put"}\NormalTok{, }\StringTok{"SK\_ratio"}\NormalTok{, }\StringTok{"sigma"}\NormalTok{, }\StringTok{"q"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"T"}\NormalTok{, }\StringTok{"user\_bs"}\NormalTok{, }\StringTok{"true\_price"}\NormalTok{, }\StringTok{"expiration"}\NormalTok{)}
\CommentTok{\# df\_ens \textless{}{-} df[(df$ticker == "NFLX" | df$ticker == "NVDA") \& df$user\_bs \textless{} 10, subset]}
\NormalTok{df\_ens }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{ticker }\SpecialCharTok{==} \StringTok{"NFLX"} \SpecialCharTok{\&}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{call\_put }\SpecialCharTok{==} \StringTok{"calls"}\NormalTok{, subset]}

\FunctionTok{head}\NormalTok{(df\_ens)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 12
##   ticker     S     K call_put SK_ratio sigma     q      r      T user_bs
##   <chr>  <dbl> <dbl> <chr>       <dbl> <dbl> <dbl>  <dbl>  <dbl>   <dbl>
## 1 NFLX    86.1    40 calls        2.15 0.327     0 0.0387 0.0137    46.1
## 2 NFLX    86.1    45 calls        1.91 0.327     0 0.0387 0.0137    41.1
## 3 NFLX    86.1    50 calls        1.72 0.327     0 0.0387 0.0137    36.1
## 4 NFLX    86.1    60 calls        1.44 0.327     0 0.0387 0.0137    26.2
## 5 NFLX    86.1    70 calls        1.23 0.327     0 0.0387 0.0137    16.2
## 6 NFLX    86.1    72 calls        1.20 0.327     0 0.0387 0.0137    14.2
## # i 2 more variables: true_price <dbl>, expiration <date>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_ens }\OtherTok{\textless{}{-}}\NormalTok{ df\_ens }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{snapshot\_date =} \FunctionTok{as.Date}\NormalTok{(expiration) }\SpecialCharTok{{-}} \FunctionTok{round}\NormalTok{(T }\SpecialCharTok{*} \DecValTok{365}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{snapshot\_month =} \FunctionTok{format}\NormalTok{(snapshot\_date, }\StringTok{"\%m"}\NormalTok{))}

\FunctionTok{head}\NormalTok{(df\_ens[}\FunctionTok{c}\NormalTok{(}\StringTok{"ticker"}\NormalTok{, }\StringTok{"true\_price"}\NormalTok{, }\StringTok{"user\_bs"}\NormalTok{, }\StringTok{"snapshot\_date"}\NormalTok{, }\StringTok{"snapshot\_month"}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   ticker true_price user_bs snapshot_date snapshot_month
##   <chr>       <dbl>   <dbl> <date>        <chr>         
## 1 NFLX         43.4    46.1 2026-01-25    01            
## 2 NFLX         40.8    41.1 2026-01-25    01            
## 3 NFLX         35.7    36.1 2026-01-25    01            
## 4 NFLX         24.8    26.2 2026-01-25    01            
## 5 NFLX         16.1    16.2 2026-01-25    01            
## 6 NFLX         12.9    14.2 2026-01-25    01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(df\_ens}\SpecialCharTok{$}\NormalTok{snapshot\_date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2026-01-25" "2026-02-26" "2026-03-26" "2026-05-25"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_en }\OtherTok{\textless{}{-}}\NormalTok{ df\_ens }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_max}\NormalTok{(true\_price, }\AttributeTok{n =} \DecValTok{25}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(ticker, call\_put, S, K, q, T, sigma, user\_bs, true\_price)}

\CommentTok{\# print(top\_en, row.names = FALSE, n = 25)}

\FunctionTok{kable}\NormalTok{(top\_en)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0986}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1268}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0563}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0423}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1408}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1408}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1549}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1549}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
ticker
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
call\_put
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
S
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
K
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
q
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
T
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sigma
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
user\_bs
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
true\_price
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
NFLX & calls & 86.12 & 15 & 0 & 1.8931507 & 0.3266234 & 72.0965437 &
1246.00 \\
NFLX & calls & 86.12 & 15 & 0 & 0.9726027 & 0.3266234 & 71.6257166 &
1205.85 \\
NFLX & calls & 86.12 & 10 & 0 & 0.3013699 & 0.3266234 & 76.2299961 &
1205.68 \\
NFLX & calls & 84.59 & 10 & 0 & 0.2136986 & 0.3383830 & 74.6687155 &
1205.68 \\
NFLX & calls & 93.32 & 10 & 0 & 0.1369863 & 0.3418921 & 83.3709354 &
1205.68 \\
NFLX & calls & 86.12 & 15 & 0 & 0.3013699 & 0.3266234 & 71.2849928 &
1200.88 \\
NFLX & calls & 84.59 & 15 & 0 & 0.2136986 & 0.3383830 & 69.7080750 &
1200.88 \\
NFLX & calls & 93.32 & 15 & 0 & 0.1369863 & 0.3418921 & 78.3964032 &
1200.88 \\
NFLX & calls & 86.12 & 5 & 0 & 1.8931507 & 0.3266234 & 81.4454858 &
1127.00 \\
NFLX & calls & 84.59 & 5 & 0 & 1.8054795 & 0.3383830 & 79.8876855 &
1127.00 \\
NFLX & calls & 93.32 & 5 & 0 & 1.7287671 & 0.3418921 & 88.6419314 &
1127.00 \\
NFLX & calls & 88.60 & 5 & 0 & 1.5643836 & 0.3329827 & 83.8978824 &
1127.00 \\
NFLX & calls & 86.12 & 290 & 0 & 1.8931507 & 0.3266234 & 0.1146157 &
1030.20 \\
NFLX & calls & 84.59 & 290 & 0 & 1.8054795 & 0.3383830 & 0.1071885 &
1030.20 \\
NFLX & calls & 93.32 & 290 & 0 & 1.7287671 & 0.3418921 & 0.2059172 &
1030.20 \\
NFLX & calls & 88.60 & 290 & 0 & 1.5643836 & 0.3329827 & 0.0674728 &
1030.20 \\
NFLX & calls & 86.12 & 300 & 0 & 1.3917808 & 0.3266234 & 0.0152592 &
1015.20 \\
NFLX & calls & 84.59 & 300 & 0 & 1.3041096 & 0.3383830 & 0.0127303 &
1015.20 \\
NFLX & calls & 93.32 & 300 & 0 & 1.2273973 & 0.3418921 & 0.0268161 &
1015.20 \\
NFLX & calls & 88.60 & 300 & 0 & 1.0630137 & 0.3329827 & 0.0041087 &
1015.20 \\
NFLX & calls & 86.12 & 270 & 0 & 0.9726027 & 0.3266234 & 0.0035252 &
1013.05 \\
NFLX & calls & 84.59 & 270 & 0 & 0.8849315 & 0.3383830 & 0.0022558 &
1013.05 \\
NFLX & calls & 93.32 & 270 & 0 & 0.8082192 & 0.3418921 & 0.0048572 &
1013.05 \\
NFLX & calls & 88.60 & 270 & 0 & 0.6438356 & 0.3329827 & 0.0002034 &
1013.05 \\
NFLX & calls & 86.12 & 270 & 0 & 1.8931507 & 0.3266234 & 0.1803873 &
997.05 \\
NFLX & calls & 84.59 & 270 & 0 & 1.8054795 & 0.3383830 & 0.1682804 &
997.05 \\
NFLX & calls & 93.32 & 270 & 0 & 1.7287671 & 0.3418921 & 0.3163944 &
997.05 \\
NFLX & calls & 88.60 & 270 & 0 & 1.5643836 & 0.3329827 & 0.1126904 &
997.05 \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{max\_val }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(}\FunctionTok{max}\NormalTok{(df\_ens}\SpecialCharTok{$}\NormalTok{user\_bs, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
               \FunctionTok{max}\NormalTok{(df\_ens}\SpecialCharTok{$}\NormalTok{true\_price, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}

\FunctionTok{ggplot}\NormalTok{(df\_ens, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ user\_bs, }\AttributeTok{y =}\NormalTok{ true\_price, }\AttributeTok{color =}\NormalTok{ snapshot\_month)) }\SpecialCharTok{+}
  \FunctionTok{geom\_blank}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ max\_val, }\AttributeTok{y =}\NormalTok{ max\_val)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Black{-}Scholes price"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Market price"}\NormalTok{, }\AttributeTok{color =} \StringTok{"Month"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{analysis_p2_files/analysis_p2_files/figure-latex/date_scatter-1.pdf}}

\section{Regresní analýza}\label{regresnuxed-analuxfdza}

\end{document}
