services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: fin_db
    restart: always
    environment:
      POSTGRES_DB: financedata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5431
    volumes:
      - ./db_script.sql:/docker-entrypoint-initdb.d/db_script.sql
      - timescaledb:/var/lib/postgresql/data

volumes:
  timescaledb:
